services:
  nginx:
    build: ./nginx
    ports:
      - "8082:80"
    volumes:
      - static-volume:/app/playterminal/collected_static/
    restart: always

  python-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8010:8010"
    volumes:
      - static-volume:/app/playterminal/collected_static/
      - db-data:/app/data
    env_file:
      - .env.local
    restart: always

volumes:
  static-volume:
  db-data:
