services:
  playterminal-nginx:
    image: tonyo/playterminal-nginx
    pull_policy: always
    build: ./nginx
    x-ports:
      - playtermin.al:80/https
    ports:
      - "8082:80"
    volumes:
      - static-volume:/app/playterminal/collected_static/
    restart: always

  playterminal-server:
    image: tonyo/playterminal-server
    pull_policy: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8010:8010"
    volumes:
      - static-volume:/app/playterminal/collected_static/
      - db-data:/app/data
    env_file:
      - .env.local
    restart: always

volumes:
  static-volume:
  db-data:
